name: Postman CLI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run Postman Collection
        uses: postmanlabs/postman-cli-action@v1
        with:
          api-key: ${{ secrets.POSTMAN_API_KEY }}
          command: >
            collection run
            47255817-3209ff1c-dece-4b56-9fb6-69d334fbffc5
            -e 47255817-f796e283-e660-4c6b-9b2e-082e622d5ac0
